name: deepfake-detection
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - pip:
    - kaggle
    - opencv-python-headless
